(require 'ert)
(require 'edn)

(ert-deftest whitespace ()
  :tags '(edn)
  (should (null (edn-parse "")))
  (should (null (edn-parse " ")))
  (should (null (edn-parse "   ")))
  (should (null (edn-parse "	")))
  (should (null (edn-parse "		")))
  (should (null (edn-parse ",")))
  (should (null (edn-parse ",,,,")))
  (should (null (edn-parse "	  , ,
")))
  (should (null (edn-parse"
  ,, 	"))))

(ert-deftest symbols ()
  :tags '(edn symbol)
  (should (equal 'foo (edn-parse "foo")))
  (should (equal 'foo\. (edn-parse "foo.")))
  (should (equal '%foo\. (edn-parse "%foo.")))
  (should (equal 'foo/bar (edn-parse "foo/bar")))
  (equal 'some\#sort\#of\#symbol (edn-parse "some#sort#of#symbol"))
  (equal 'truefalse (edn-parse "truefalse"))
  (equal 'true. (edn-parse "true."))
  (equal '/ (edn-parse "/"))
  (should (equal '.true (edn-parse ".true")))
  (should (equal 'some:sort:of:symbol (edn-parse "some:sort:of:symbol")))
  (equal 'foo-bar (edn-parse "foo-bar")))

(ert-deftest booleans ()
  :tags '(edn boolean)
  (should (equal t (edn-parse "true")))
  (should (equal nil (edn-parse "false "))))

(ert-deftest characters ()
  :tags '(edn characters)
  (should (equal 97 (edn-parse "\\a")))
  (should (equal 960 (edn-parse "\\u03C0")))
  (should (equal 'newline (edn-parse "\\newline"))))

(ert-deftest elision ()
  :tags '(edn elision)
  (should-not (edn-parse "#_foo"))
  (should-not (edn-parse "#_ 123"))
  (should-not (edn-parse "#_ \\a")))
